language: "perl"

sudo: false

addons:
  apt:
    packages:
    - libbz2-dev
    - libcurl4-openssl-dev
    - liblzma-dev

os:
  - linux
  - osx

osx_image: xcode7.3

env:
  - ALIEN_INSTALL_TYPE=share DEP_INSTALL_TYPE=share
  - ALIEN_INSTALL_TYPE=share DEP_INSTALL_TYPE=default
  - ALIEN_INSTALL_TYPE=default DEP_INSTALL_TYPE=default
  - ALIEN_INSTALL_TYPE=default DEP_INSTALL_TYPE=share

matrix:
  exclude:
    - os: osx
      perl: "5.14"
  allow_failures:
    - os: osx

perl:
  - "5.14"
  - "5.26"

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      eval "$($HOME/perl5/perlbrew/bin/perlbrew env $TRAVIS_PERL_VERSION)"
      export PATH=${PERLBREW_PATH:-$PERLBREW_ROOT/bin}:$PATH
      perlbrew --quiet install-cpanm --force
      cpanm --version
      env | grep -i ^perl
      export SSL_DIR=/usr/local/Cellar/openssl/1.0.2j
    fi
install:
  - ALIEN_INSTALL_TYPE=$DEP_INSTALL_TYPE cpanm --installdeps -n -q .
before_script:
  - perl -MAlien::curl -Mv5.10 -le 'say Alien::curl->cflags; say Alien::curl->libs;'
  - perl -MAlien::Libbz2 -Mv5.10 -le 'say Alien::Libbz2->cflags; say Alien::Libbz2->libs;'
script:
  - perl Makefile.PL && make test TEST_VERBOSE=1
after_failure:
  - cat _alien/state.json
