---
abstract: 'Installation of HTSlib for Perl'
author:
  - 'Rishi Nag <rishi@ebi.ac.uk>'
build_requires: {}
configure_requires:
  Alien::Base::ModuleBuild: '0'
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4216, CPAN::Meta::Converter version 2.150005'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-HTSlib
provides:
  Alien::HTSlib:
    file: lib/Alien/HTSlib.pm
    version: '0.03'
requires:
  Alien::Base: '0'
  File::ShareDir: '1.00'
  perl: v5.8.1
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
